package com.smartlocalstorage.smart_local_storage

import android.os.Build
import android.os.Handler
import android.os.Looper
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import androidx.annotation.NonNull
import androidx.annotation.RequiresApi
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result
import java.security.KeyStore
import java.util.concurrent.Executors
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/** SmartLocalStoragePlugin
 *  - getDocumentsPath: the app's private files directory
 *  - encrypt / decrypt: AES-256-GCM with a key that lives in the Android
 *    Keystore (the key never leaves secure hardware / the Keystore).
 *    Output layout: 12-byte IV + ciphertext + 16-byte tag. */
class SmartLocalStoragePlugin : FlutterPlugin, MethodCallHandler {
  private lateinit var channel: MethodChannel
  private var filesDirPath: String? = null
  private val worker = Executors.newSingleThreadExecutor()
  private val mainHandler = Handler(Looper.getMainLooper())

  override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
    channel = MethodChannel(flutterPluginBinding.binaryMessenger, "smart_local_storage")
    channel.setMethodCallHandler(this)
    filesDirPath = flutterPluginBinding.applicationContext.filesDir.path
  }

  override fun onMethodCall(call: MethodCall, result: Result) {
    when (call.method) {
      "getDocumentsPath" -> result.success(filesDirPath)
      "encrypt", "decrypt" -> {
        val input = call.arguments as? ByteArray
        if (input == null) {
          result.error("bad_args", "Expected a byte array.", null)
          return
        }
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
          result.error("unsupported", "Encryption needs Android 6.0 (API 23) or newer.", null)
          return
        }
        val encrypting = call.method == "encrypt"
        // Crypto runs off the UI thread so big boxes never freeze the app.
        worker.execute {
          try {
            val out = if (encrypting) encryptBytes(input) else decryptBytes(input)
            mainHandler.post { result.success(out) }
          } catch (e: Exception) {
            mainHandler.post { result.error("crypto_failed", e.message, null) }
          }
        }
      }
      else -> result.notImplemented()
    }
  }

  @RequiresApi(Build.VERSION_CODES.M)
  private fun secretKey(): SecretKey {
    val store = KeyStore.getInstance("AndroidKeyStore")
    store.load(null)
    val existing = store.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry
    if (existing != null) return existing.secretKey
    val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
    generator.init(
      KeyGenParameterSpec.Builder(
        KEY_ALIAS,
        KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
      )
        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
        .setKeySize(256)
        .build()
    )
    return generator.generateKey()
  }

  @RequiresApi(Build.VERSION_CODES.M)
  private fun encryptBytes(plain: ByteArray): ByteArray {
    val cipher = Cipher.getInstance("AES/GCM/NoPadding")
    cipher.init(Cipher.ENCRYPT_MODE, secretKey())
    val iv = cipher.iv // 12 bytes, generated by the Keystore
    return iv + cipher.doFinal(plain)
  }

  @RequiresApi(Build.VERSION_CODES.M)
  private fun decryptBytes(data: ByteArray): ByteArray {
    require(data.size > IV_SIZE) { "Data is too short to be encrypted." }
    val cipher = Cipher.getInstance("AES/GCM/NoPadding")
    cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(128, data, 0, IV_SIZE))
    return cipher.doFinal(data, IV_SIZE, data.size - IV_SIZE)
  }

  override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
    channel.setMethodCallHandler(null)
  }

  companion object {
    private const val KEY_ALIAS = "smart_local_cache_aes_key"
    private const val IV_SIZE = 12
  }
}
